name: docx_template
description: A Docx template engine.
version: 0.3.3
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  archive: ^3.3.5
  xml: ^6.2.2
  collection: ^1.17.0
  path: ^1.8.3
dev_dependencies:
  #pedantic: ^1.11.1
  test: ^1.22.1
